<?php
require __DIR__.'/includes/bootstrap.php';require_auth();if(!identity_schema_ready())redirect('upgrade.php');$uid=(int)user()['id'];ensure_profile($uid);$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();
 try{
  $display=trim($_POST['display_name']??'');if($display==='')throw new RuntimeException('Display name is required.');$website=trim($_POST['website']??'');if($website!==''&&!filter_var($website,FILTER_VALIDATE_URL))throw new RuntimeException('Enter a complete website URL including https://.');
  $avatar=save_uploaded_image('avatar','avatars',$uid);$banner=save_uploaded_image('banner','banners',$uid);db()->beginTransaction();db()->prepare('UPDATE users SET display_name=? WHERE id=?')->execute([$display,$uid]);$sql='UPDATE user_profiles SET bio=?,location=?,website=?,visibility=?'.($avatar?',avatar_path=?':'').($banner?',banner_path=?':'').' WHERE user_id=?';$args=[trim($_POST['bio']??''),trim($_POST['location']??''),$website,in_array($_POST['visibility']??'public',['public','members','private'],true)?$_POST['visibility']:'public'];if($avatar)$args[]=$avatar;if($banner)$args[]=$banner;$args[]=$uid;db()->prepare($sql)->execute($args);replace_selections('user_identity_types','identity_type_id',$uid,$_POST['identity_types']??[]);replace_selections('user_interests','interest_id',$uid,$_POST['interests']??[]);replace_selections('user_universes','universe_id',$uid,$_POST['universes']??[]);db()->prepare('DELETE FROM user_social_links WHERE user_id=?')->execute([$uid]);$ins=db()->prepare('INSERT INTO user_social_links(user_id,platform,url,sort_order) VALUES(?,?,?,?)');foreach(($_POST['social_platform']??[]) as $i=>$platform){$platform=trim($platform);$url=trim($_POST['social_url'][$i]??'');if($platform!==''&&filter_var($url,FILTER_VALIDATE_URL))$ins->execute([$uid,$platform,$url,$i]);}db()->commit();flash('success','Profile updated.');redirect('profile.php?u='.urlencode(user()['username']));
 }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();$error=$e->getMessage();}
}
$p=profile_for_user($uid);$selected=function($table,$join,$fk)use($uid){return array_map('intval',array_column(selections($table,$join,$fk,$uid),'id'));};$identityIds=$selected('identity_types','user_identity_types','identity_type_id');$interestIds=$selected('interests','user_interests','interest_id');$universeIds=$selected('universes','user_universes','universe_id');$social=db()->prepare('SELECT * FROM user_social_links WHERE user_id=? ORDER BY sort_order,id');$social->execute([$uid]);$social=$social->fetchAll();while(count($social)<3)$social[]=['platform'=>'','url'=>''];app_header('Edit Profile');
?><section class="dashboard-hero"><p class="eyebrow">USER IDENTITY</p><h1>Edit Profile</h1></section><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif?><form class="profile-form" method="post" enctype="multipart/form-data"><?=csrf_field()?><section class="app-card form-grid"><label>Display name<input name="display_name" required value="<?=e($p['display_name'])?>"></label><label>Location<input name="location" value="<?=e($p['location'])?>"></label><label class="full">Bio<textarea name="bio" maxlength="1000"><?=e($p['bio'])?></textarea></label><label>Website<input type="url" name="website" value="<?=e($p['website'])?>"></label><label>Visibility<select name="visibility"><option value="public">Public</option><option value="members" <?=$p['visibility']==='members'?'selected':''?>>Members only</option><option value="private" <?=$p['visibility']==='private'?'selected':''?>>Private</option></select></label><label>New avatar<input type="file" name="avatar" accept="image/jpeg,image/png,image/webp,image/gif"></label><label>New banner<input type="file" name="banner" accept="image/jpeg,image/png,image/webp,image/gif"></label></section><section class="app-card"><h2>Identity</h2><div class="choice-grid"><?php foreach(taxonomy('identity_types') as $x):?><label class="choice"><input type="checkbox" name="identity_types[]" value="<?=$x['id']?>" <?=in_array((int)$x['id'],$identityIds,true)?'checked':''?>><span><?=e($x['name'])?></span></label><?php endforeach?></div></section><section class="app-card"><h2>Interests</h2><div class="choice-grid"><?php foreach(taxonomy('interests') as $x):?><label class="choice"><input type="checkbox" name="interests[]" value="<?=$x['id']?>" <?=in_array((int)$x['id'],$interestIds,true)?'checked':''?>><span><?=e($x['name'])?></span></label><?php endforeach?></div></section><section class="app-card"><h2>Favorite Universes</h2><div class="choice-grid"><?php foreach(taxonomy('universes') as $x):?><label class="choice"><input type="checkbox" name="universes[]" value="<?=$x['id']?>" <?=in_array((int)$x['id'],$universeIds,true)?'checked':''?>><span><?=e(($x['icon']?$x['icon'].' ':'').$x['name'])?></span></label><?php endforeach?></div></section><section class="app-card"><h2>Social Links</h2><?php foreach($social as $x):?><div class="social-row"><input name="social_platform[]" placeholder="Platform" value="<?=e($x['platform'])?>"><input type="url" name="social_url[]" placeholder="https://" value="<?=e($x['url'])?>"></div><?php endforeach?></section><div class="form-actions"><a class="button ghost" href="profile.php?u=<?=urlencode(user()['username'])?>">Cancel</a><button class="button primary">Save Profile</button></div></form><?php app_footer();
