<?php
require __DIR__.'/includes/bootstrap.php';require_auth();
if(!identity_schema_ready()){if((user()['role']??'')==='admin')redirect('upgrade.php');http_response_code(503);exit('User Identity has not been installed yet.');}
$uid=(int)user()['id'];ensure_profile($uid);$p=profile_for_user($uid);$step=max(1,min(6,(int)($_GET['step']??$p['onboarding_step']??1)));$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$step=max(1,min(6,(int)($_POST['step']??1)));
 try{
  if(isset($_POST['skip'])){$next=min(6,$step+1);db()->prepare('UPDATE user_profiles SET onboarding_step=? WHERE user_id=?')->execute([$next,$uid]);redirect('onboarding.php?step='.$next);}
  if($step===1){db()->prepare('UPDATE user_profiles SET onboarding_step=2 WHERE user_id=?')->execute([$uid]);redirect('onboarding.php?step=2');}
  if($step===2){replace_selections('user_identity_types','identity_type_id',$uid,$_POST['identity_types']??[]);db()->prepare('UPDATE user_profiles SET onboarding_step=3 WHERE user_id=?')->execute([$uid]);redirect('onboarding.php?step=3');}
  if($step===3){replace_selections('user_interests','interest_id',$uid,$_POST['interests']??[]);db()->prepare('UPDATE user_profiles SET onboarding_step=4 WHERE user_id=?')->execute([$uid]);redirect('onboarding.php?step=4');}
  if($step===4){replace_selections('user_universes','universe_id',$uid,$_POST['universes']??[]);db()->prepare('UPDATE user_profiles SET onboarding_step=5 WHERE user_id=?')->execute([$uid]);redirect('onboarding.php?step=5');}
  if($step===5){
   $display=trim($_POST['display_name']??'');if($display==='')throw new RuntimeException('Display name is required.');
   $website=trim($_POST['website']??'');if($website!==''&&!filter_var($website,FILTER_VALIDATE_URL))throw new RuntimeException('Enter a complete website URL including https://.');
   $avatar=save_uploaded_image('avatar','avatars',$uid);$banner=save_uploaded_image('banner','banners',$uid);
   db()->prepare('UPDATE users SET display_name=? WHERE id=?')->execute([$display,$uid]);
   $sql='UPDATE user_profiles SET bio=?,location=?,website=?,visibility=?,onboarding_step=6'.($avatar?',avatar_path=?':'').($banner?',banner_path=?':'').' WHERE user_id=?';
   $args=[trim($_POST['bio']??''),trim($_POST['location']??''),$website,in_array($_POST['visibility']??'public',['public','members','private'],true)?$_POST['visibility']:'public'];if($avatar)$args[]=$avatar;if($banner)$args[]=$banner;$args[]=$uid;db()->prepare($sql)->execute($args);redirect('onboarding.php?step=6');
  }
  if($step===6){db()->prepare('UPDATE user_preferences SET email_newsletter=?,email_community_updates=?,email_product_updates=? WHERE user_id=?')->execute([isset($_POST['email_newsletter'])?1:0,isset($_POST['email_community_updates'])?1:0,isset($_POST['email_product_updates'])?1:0,$uid]);db()->prepare('UPDATE user_profiles SET onboarding_completed_at=NOW(),onboarding_step=6 WHERE user_id=?')->execute([$uid]);flash('success','Your Multiverse identity is ready.');redirect('profile.php?u='.urlencode(user()['username']));}
 }catch(Throwable $e){$error=$e->getMessage();}
}
$selectedIds=function($table,$join,$fk)use($uid){return array_map('intval',array_column(selections($table,$join,$fk,$uid),'id'));};
$ids=$step===2?$selectedIds('identity_types','user_identity_types','identity_type_id'):($step===3?$selectedIds('interests','user_interests','interest_id'):($step===4?$selectedIds('universes','user_universes','universe_id'):[]));
$p=profile_for_user($uid);app_header('Create Your Identity');
?><section class="onboarding-shell"><div class="onboarding-top"><div><p class="eyebrow">USER IDENTITY</p><h1>Create your Multiverse identity</h1></div><strong>Step <?=$step?> of 6</strong></div><div class="progress"><span style="width:<?=($step/6)*100?>%"></span></div><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif?><form class="onboarding-card" method="post" enctype="multipart/form-data"><?=csrf_field()?><input type="hidden" name="step" value="<?=$step?>">
<?php if($step===1):?><h2>Welcome to Geek Nation Multiverse</h2><p>Build a profile around the fandoms, creative work, and communities that make you a geek. You can update everything later.</p>
<?php elseif($step===2):?><h2>How do you identify?</h2><p class="muted">Choose every role that fits.</p><div class="choice-grid"><?php foreach(taxonomy('identity_types') as $x):?><label class="choice"><input type="checkbox" name="identity_types[]" value="<?=$x['id']?>" <?=in_array((int)$x['id'],$ids,true)?'checked':''?>><span><?=e($x['name'])?></span></label><?php endforeach?></div>
<?php elseif($step===3):?><h2>What are you into?</h2><div class="choice-grid"><?php foreach(taxonomy('interests') as $x):?><label class="choice"><input type="checkbox" name="interests[]" value="<?=$x['id']?>" <?=in_array((int)$x['id'],$ids,true)?'checked':''?>><span><?=e($x['name'])?></span></label><?php endforeach?></div>
<?php elseif($step===4):?><h2>Choose your favorite universes</h2><div class="choice-grid universe-choices"><?php foreach(taxonomy('universes') as $x):?><label class="choice"><input type="checkbox" name="universes[]" value="<?=$x['id']?>" <?=in_array((int)$x['id'],$ids,true)?'checked':''?>><span><?=e(($x['icon']?' '.$x['icon'].' ':'').$x['name'])?></span></label><?php endforeach?></div>
<?php elseif($step===5):?><h2>Build your profile</h2><div class="form-grid"><label>Display name<input name="display_name" required value="<?=e($p['display_name'])?>"></label><label>Location<input name="location" value="<?=e($p['location'])?>"></label><label class="full">Bio<textarea name="bio" maxlength="1000"><?=e($p['bio'])?></textarea></label><label>Website<input type="url" name="website" placeholder="https://" value="<?=e($p['website'])?>"></label><label>Visibility<select name="visibility"><option value="public">Public</option><option value="members" <?=$p['visibility']==='members'?'selected':''?>>Members only</option><option value="private" <?=$p['visibility']==='private'?'selected':''?>>Private</option></select></label><label>Avatar<input type="file" name="avatar" accept="image/jpeg,image/png,image/webp,image/gif"></label><label>Banner<input type="file" name="banner" accept="image/jpeg,image/png,image/webp,image/gif"></label></div>
<?php else:$pref=db()->query('SELECT * FROM user_preferences WHERE user_id='.$uid)->fetch();?><h2>Notification preferences</h2><div class="stacked-choices"><label><input type="checkbox" name="email_newsletter" <?=$pref['email_newsletter']?'checked':''?>> Geek Nation newsletter</label><label><input type="checkbox" name="email_community_updates" <?=$pref['email_community_updates']?'checked':''?>> Community updates</label><label><input type="checkbox" name="email_product_updates" <?=$pref['email_product_updates']?'checked':''?>> Product and platform updates</label></div><?php endif?>
<div class="onboarding-actions"><?php if($step>1):?><a class="button ghost" href="onboarding.php?step=<?=$step-1?>">Back</a><?php endif?><div></div><?php if(in_array($step,[2,3,4,5],true)):?><button class="button ghost" name="skip" value="1">Skip for now</button><?php endif?><button class="button primary"><?=$step===6?'Complete Profile':'Continue'?></button></div></form></section><?php app_footer();
