<?php
require __DIR__.'/includes/bootstrap.php';
if(!identity_schema_ready()){http_response_code(503);exit('User Identity has not been installed yet.');}
$username=strtolower(trim($_GET['u']??''));if($username===''){if(user())redirect('profile.php?u='.urlencode(user()['username']));redirect('login.php');}
$s=db()->prepare("SELECT id FROM users WHERE username=? AND status='active' LIMIT 1");$s->execute([$username]);$id=(int)($s->fetchColumn()?:0);if(!$id){http_response_code(404);exit('Profile not found.');}
$p=profile_for_user($id);$viewer=user();$isOwner=$viewer&&(int)$viewer['id']===$id;$isAdmin=$viewer&&($viewer['role']??'')==='admin';
if($p['visibility']==='private'&&!$isOwner&&!$isAdmin){http_response_code(403);exit('This profile is private.');}
if($p['visibility']==='members'&&!$viewer){flash('error','Sign in to view this member profile.');redirect('login.php');}
$identities=selections('identity_types','user_identity_types','identity_type_id',$id);$interests=selections('interests','user_interests','interest_id',$id);$universes=selections('universes','user_universes','universe_id',$id);$social=db()->prepare('SELECT * FROM user_social_links WHERE user_id=? ORDER BY sort_order,id');$social->execute([$id]);$social=$social->fetchAll();$completion=$isOwner?profile_completion($p):null;
app_header($p['display_name']);
?><section class="profile-hero" style="<?php if($p['banner_path']):?>background-image:linear-gradient(180deg,rgba(5,5,11,.18),#05050b),url('<?=e(base_url($p['banner_path']))?>')<?php endif?>"><div class="profile-avatar"><?php if($p['avatar_path']):?><img src="<?=e(base_url($p['avatar_path']))?>" alt="<?=e($p['display_name'])?>"><?php else:?><span><?=e(strtoupper(substr($p['display_name'],0,1)))?></span><?php endif?></div><div class="profile-title"><p class="eyebrow">MULTIVERSE PROFILE</p><h1><?=e($p['display_name'])?></h1><p>@<?=e($p['username'])?><?php if($p['location']):?> · <?=e($p['location'])?><?php endif?></p></div><?php if($isOwner):?><a class="button primary" href="edit-profile.php">Edit Profile</a><?php endif?></section>
<?php if($isOwner&&$completion):?><section class="completion-card"><div><strong>Profile completion: <?=$completion['percent']?>%</strong><div class="progress"><span style="width:<?=$completion['percent']?>%"></span></div></div><div class="completion-checks"><?php foreach($completion['checks'] as $label=>$done):?><span class="<?=$done?'done':''?>"><?=$done?'✓':'○'?> <?=e($label)?></span><?php endforeach?></div></section><?php endif?>
<section class="profile-grid"><article class="app-card profile-main"><h2>About</h2><p><?=nl2br(e($p['bio']?:'This member has not added a bio yet.'))?></p><?php if($p['website']):?><p><a href="<?=e($p['website'])?>" target="_blank" rel="noopener">Visit website</a></p><?php endif?><?php if($social):?><h3>Social links</h3><div class="tag-list"><?php foreach($social as $x):?><a class="tag" href="<?=e($x['url'])?>" target="_blank" rel="noopener"><?=e($x['platform'])?></a><?php endforeach?></div><?php endif?></article><aside class="profile-side"><article class="app-card"><h2>Identity</h2><div class="tag-list"><?php foreach($identities as $x):?><span class="tag accent"><?=e($x['name'])?></span><?php endforeach?><?php if(!$identities):?><span class="muted">Not selected yet.</span><?php endif?></div></article><article class="app-card"><h2>Interests</h2><div class="tag-list"><?php foreach($interests as $x):?><span class="tag"><?=e($x['name'])?></span><?php endforeach?><?php if(!$interests):?><span class="muted">Not selected yet.</span><?php endif?></div></article><article class="app-card"><h2>Favorite Universes</h2><div class="tag-list"><?php foreach($universes as $x):?><span class="tag universe-tag"><?=e(($x['icon']?$x['icon'].' ':'').$x['name'])?></span><?php endforeach?><?php if(!$universes):?><span class="muted">Not selected yet.</span><?php endif?></div></article><article class="app-card"><h2>Member Since</h2><p><?=e(date('F Y',strtotime($p['created_at'])))?></p></article></aside></section><?php app_footer();
