<?php require __DIR__.'/../includes/bootstrap.php';
if(!academy_ready()){app_header('Multiverse Academy');?><section class="form-card"><h1>Multiverse Academy is not installed</h1><?php if((user()['role']??'')==='admin'):?><a class="button primary" href="../upgrade-multiverse-academy.php">Install Academy</a><?php endif?></section><?php app_footer();exit;}
$q=trim($_GET['q']??'');$category=trim($_GET['category']??'');$level=trim($_GET['level']??'');
$sql="SELECT c.*,u.display_name owner_name,(SELECT COUNT(*) FROM academy_lessons l WHERE l.course_id=c.id) lesson_count,(SELECT COUNT(*) FROM academy_enrollments e WHERE e.course_id=c.id AND e.status<>'cancelled') enrollment_count FROM academy_courses c JOIN users u ON u.id=c.owner_user_id WHERE c.status='approved'";$args=[];
if($q!==''){$sql.=' AND (c.title LIKE ? OR c.subtitle LIKE ? OR c.description LIKE ?)';$args=array_fill(0,3,'%'.$q.'%');}
if($category!==''){$sql.=' AND c.category=?';$args[]=$category;}if($level!==''){$sql.=' AND c.level=?';$args[]=$level;}$sql.=' ORDER BY c.is_featured DESC,c.created_at DESC';$s=db()->prepare($sql);$s->execute($args);$courses=$s->fetchAll();
$categories=db()->query("SELECT DISTINCT category FROM academy_courses WHERE status='approved' ORDER BY category")->fetchAll(PDO::FETCH_COLUMN);
app_header('Multiverse Academy');?><section class="dashboard-hero academy-hero"><p class="eyebrow">LEARN ACROSS THE MULTIVERSE</p><h1>Multiverse Academy</h1><p>Courses, workshops, tutorials, and live learning from creators, experts, and communities.</p><form class="hero-search" method="get"><input name="q" value="<?=e($q)?>" placeholder="Search courses"><select name="category"><option value="">All categories</option><?php foreach($categories as $cat):?><option value="<?=e($cat)?>" <?=$category===$cat?'selected':''?>><?=e(ucwords(str_replace('_',' ',$cat)))?></option><?php endforeach?></select><select name="level"><option value="">All levels</option><?php foreach(academy_levels() as $k=>$v):?><option value="<?=$k?>" <?=$level===$k?'selected':''?>><?=$v?></option><?php endforeach?></select><button>Search</button></form><?php if(user()):?><p><a class="button primary" href="create.php">Create Course</a> <a class="button ghost" href="dashboard.php">My Academy</a></p><?php endif?></section>
<section class="course-grid"><?php foreach($courses as $course):?><article class="course-card"><?php if($course['thumbnail_path']):?><img src="<?=e(base_url($course['thumbnail_path']))?>" alt=""><?php endif?><div class="course-card-body"><p class="eyebrow"><?=e(strtoupper(str_replace('_',' ',$course['category'])))?></p><h2><a href="view.php?slug=<?=urlencode($course['slug'])?>"><?=e($course['title'])?></a></h2><p><?=e($course['subtitle'])?></p><div class="pill-row"><span class="pill"><?=e(academy_levels()[$course['level']]??$course['level'])?></span><span class="pill"><?=(int)$course['lesson_count']?> lessons</span><span class="pill"><?=(int)$course['enrollment_count']?> learners</span></div><p><strong><?=$course['price']>0?'$'.number_format((float)$course['price'],2):'Free'?></strong></p></div></article><?php endforeach?><?php if(!$courses):?><div class="empty-state"><h2>No courses found</h2><p>Try another search or create the first Academy course.</p></div><?php endif?></section><?php app_footer();
