<?php
require __DIR__.'/../includes/bootstrap.php';require_admin();if(!identity_schema_ready())redirect('upgrade.php');
$allowed=['identity_types'=>['Community Identities','name'],'interests'=>['Interests','name']];$type=$_GET['type']??'identity_types';if(!isset($allowed[$type]))$type='identity_types';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=$_POST['action']??'';
 if($action==='add'){$name=trim($_POST['name']??'');if($name!==''){$slug=strtolower(trim(preg_replace('/[^a-z0-9]+/i','-',$name),'-'));if($type==='universes')db()->prepare('INSERT INTO universes(name,slug,icon,sort_order) VALUES(?,?,?,?)')->execute([$name,$slug,trim($_POST['icon']??''),(int)($_POST['sort_order']??0)]);else db()->prepare("INSERT INTO {$type}(name,slug,sort_order) VALUES(?,?,?)")->execute([$name,$slug,(int)($_POST['sort_order']??0)]);flash('success','Option added.');}}
 if($action==='toggle')db()->prepare("UPDATE {$type} SET is_active=1-is_active WHERE id=?")->execute([(int)$_POST['id']]);
 redirect('admin/identity.php?type='.$type);
}
$rows=db()->query("SELECT * FROM {$type} ORDER BY sort_order,name")->fetchAll();app_header('Identity Management');
?><section class="dashboard-hero"><p class="eyebrow">ADMINISTRATION</p><h1>User Identity</h1><div class="admin-tabs"><?php foreach($allowed as $key=>$meta):?><a class="button <?=$key===$type?'primary':'ghost'?> small" href="?type=<?=$key?>"><?=e($meta[0])?></a><?php endforeach?></div></section><section class="dashboard-grid admin-identity-grid"><form class="app-card" method="post"><?=csrf_field()?><input type="hidden" name="action" value="add"><h2>Add <?=e(rtrim($allowed[$type][0],'s'))?></h2><label>Name<input name="name" required></label><?php if($type==='universes'):?><label>Icon or emoji<input name="icon" maxlength="30"></label><?php endif?><label>Sort order<input type="number" name="sort_order" value="0"></label><button class="button primary">Add Option</button></form><div class="table-wrap identity-table"><table><thead><tr><th>Name</th><th>Slug</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($rows as $x):?><tr><td><?=e(($x['icon']??'').' '.$x['name'])?></td><td><?=e($x['slug'])?></td><td><?=$x['is_active']?'Active':'Hidden'?></td><td><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$x['id']?>"><button class="button ghost small"><?=$x['is_active']?'Hide':'Activate'?></button></form></td></tr><?php endforeach?></tbody></table></div></section><?php app_footer();
