<?php
require __DIR__.'/../includes/bootstrap.php';require_auth();
if(!companies_schema_ready())redirect((user()['role']??'')==='admin'?'../upgrade-companies.php':'../dashboard.php');
$u=user();if($u['status']!=='active'||empty($u['email_verified_at'])){flash('error','Verify your email before submitting a company.');redirect('../dashboard.php');}
$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();
 try{
  $name=trim($_POST['name']??'');$relationship=$_POST['relationship_type']??'';$position=trim($_POST['position_title']??'');
  $allowed=['employee','founder','owner','executive','contractor','partner','advisor','fan','other'];
  if($name==='')throw new RuntimeException('Company name is required.');if(!in_array($relationship,$allowed,true))throw new RuntimeException('Tell us how you are connected to this company.');
  if($relationship!=='fan'&&$position==='')throw new RuntimeException('Enter the position you hold at the company.');
  $website=trim($_POST['website']??'');if($website!==''&&!filter_var($website,FILTER_VALIDATE_URL))throw new RuntimeException('Enter a complete website URL including https://.');
  $email=trim($_POST['public_email']??'');if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))throw new RuntimeException('Enter a valid public email.');
  $year=(int)($_POST['founded_year']??0);if($year && ($year<1500||$year>(int)date('Y')))throw new RuntimeException('Enter a valid founded year.');
  db()->beginTransaction();
  $slug=company_slug($name);$s=db()->prepare("INSERT INTO companies(name,slug,short_description,description,website,public_email,phone,location,category,founded_year,status,submitted_by) VALUES(?,?,?,?,?,?,?,?,?,?,'pending',?)");
  $s->execute([$name,$slug,trim($_POST['short_description']??''),trim($_POST['description']??''),$website,$email,trim($_POST['phone']??''),trim($_POST['location']??''),trim($_POST['category']??''),$year?:null,(int)$u['id']]);$cid=(int)db()->lastInsertId();
  $companyRole=$relationship==='fan'?'fan':'pending_owner';$membershipStatus=$relationship==='fan'?'pending':'pending';
  db()->prepare('INSERT INTO company_members(company_id,user_id,relationship_type,position_title,company_role,status) VALUES(?,?,?,?,?,?)')->execute([$cid,(int)$u['id'],$relationship,$position?:null,$companyRole,$membershipStatus]);
  db()->prepare("INSERT INTO company_approval_history(company_id,action,notes,acted_by) VALUES(?,'submitted',?,?)")->execute([$cid,$relationship==='fan'?'Submitted by a fan.':'Submitted by a claimed company representative: '.$position,(int)$u['id']]);
  db()->commit();
  try{$logo=save_uploaded_image('logo','companies/logos',$cid);$banner=save_uploaded_image('banner','companies/banners',$cid);if($logo||$banner){$sql='UPDATE companies SET '.implode(',',array_filter([$logo?'logo_path=?':null,$banner?'banner_path=?':null])).' WHERE id=?';$args=[];if($logo)$args[]=$logo;if($banner)$args[]=$banner;$args[]=$cid;db()->prepare($sql)->execute($args);}}catch(Throwable $uploadError){flash('error','Company submitted, but an image could not be saved: '.$uploadError->getMessage());}
  flash('success',$relationship==='fan'?'Company submitted for review. Because you identified as a fan, ownership will not be assigned automatically.':'Company submitted for review. After approval, you will become Company Owner and your position will remain on the company record.');redirect('dashboard.php?id='.$cid);
 }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();$error=$e->getMessage();}
}
app_header('Submit Company');
?><section class="dashboard-hero"><p class="eyebrow">COMPANY SUBMISSION</p><h1>Submit a Company</h1><p>Any verified member may submit a company. An administrator must approve it before it becomes public.</p></section><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif?><form class="profile-form" method="post" enctype="multipart/form-data"><?=csrf_field()?><section class="app-card form-grid"><label>Company name<input name="name" required value="<?=e($_POST['name']??'')?>"></label><label>Category<input name="category" placeholder="Publisher, studio, retailer..." value="<?=e($_POST['category']??'')?>"></label><label class="full">Short description<input name="short_description" maxlength="280" value="<?=e($_POST['short_description']??'')?>"></label><label class="full">Full description<textarea name="description"><?=e($_POST['description']??'')?></textarea></label><label>Website<input type="url" name="website" placeholder="https://" value="<?=e($_POST['website']??'')?>"></label><label>Public email<input type="email" name="public_email" value="<?=e($_POST['public_email']??'')?>"></label><label>Phone<input name="phone" value="<?=e($_POST['phone']??'')?>"></label><label>Location<input name="location" value="<?=e($_POST['location']??'')?>"></label><label>Founded year<input type="number" name="founded_year" min="1500" max="<?=date('Y')?>" value="<?=e($_POST['founded_year']??'')?>"></label><label>Logo<input type="file" name="logo" accept="image/jpeg,image/png,image/webp,image/gif"></label><label>Banner<input type="file" name="banner" accept="image/jpeg,image/png,image/webp,image/gif"></label></section><section class="app-card form-grid"><div class="full"><h2>Your connection to this company</h2><p class="muted">This tells administrators whether you represent the company or are a fan helping add it.</p></div><label>Relationship<select name="relationship_type" required><option value="">Choose one</option><?php foreach(['employee'=>'Employee','founder'=>'Founder','owner'=>'Owner','executive'=>'Executive','contractor'=>'Contractor','partner'=>'Partner','advisor'=>'Advisor','fan'=>'Fan / no official affiliation','other'=>'Other official affiliation'] as $v=>$label):?><option value="<?=e($v)?>" <?=($_POST['relationship_type']??'')===$v?'selected':''?>><?=e($label)?></option><?php endforeach?></select></label><label>Position held<input name="position_title" placeholder="CEO, Marketing Director, Artist..." value="<?=e($_POST['position_title']??'')?>"><span class="field-help">Required unless you select Fan.</span></label></section><div class="form-actions"><a class="button ghost" href="index.php">Cancel</a><button class="button primary">Submit for Approval</button></div></form><?php app_footer();
