<?php
require __DIR__.'/../includes/bootstrap.php';require_auth();
if(!companies_schema_ready()){if((user()['role']??'')==='admin')redirect('upgrade-companies.php');http_response_code(503);exit('Companies are not installed yet.');}
$q=trim($_GET['q']??'');$params=[];$where="c.status='approved'";if($q!==''){$where.=' AND (c.name LIKE ? OR c.category LIKE ? OR c.location LIKE ?)';$like='%'.$q.'%';$params=[$like,$like,$like];}
$s=db()->prepare("SELECT c.*,u.display_name AS submitter_name FROM companies c JOIN users u ON u.id=c.submitted_by WHERE $where ORDER BY c.name");$s->execute($params);$companies=$s->fetchAll();
$mine=db()->prepare('SELECT c.*,cm.company_role,cm.relationship_type,cm.position_title,cm.status AS membership_status FROM companies c JOIN company_members cm ON cm.company_id=c.id WHERE cm.user_id=? ORDER BY c.updated_at DESC');$mine->execute([(int)user()['id']]);$mine=$mine->fetchAll();
app_header('Companies');
?><section class="dashboard-hero"><p class="eyebrow">ORGANIZATIONS</p><h1>Companies</h1><p class="lede">Discover companies across the Multiverse or submit one for administrator approval.</p><p><a class="button primary" href="create.php">Submit a Company</a></p></section>
<?php if($mine):?><section class="company-section"><div class="section-heading compact"><h2>Your Companies</h2></div><div class="company-grid"><?php foreach($mine as $c):?><article class="company-card"><div class="company-card-body"><span class="status-badge <?=e($c['status'])?>"><?=e(ucfirst($c['status']))?></span><h3><?=e($c['name'])?></h3><p class="muted"><?=e($c['relationship_type']==='fan'?'Fan submission':($c['position_title']?:ucwords(str_replace('_',' ',$c['company_role']))))?></p><p><a class="button ghost small" href="dashboard.php?id=<?=(int)$c['id']?>">Open</a></p></div></article><?php endforeach?></div></section><?php endif?>
<section class="company-section"><div class="section-heading compact"><h2>Approved Companies</h2></div><form class="company-search" method="get"><input name="q" value="<?=e($q)?>" placeholder="Search company, category, or location"><button class="button ghost">Search</button></form><div class="company-grid"><?php foreach($companies as $c):?><article class="company-card"><?php if($c['banner_path']):?><div class="company-card-banner" style="background-image:url('<?=e(base_url($c['banner_path']))?>')"></div><?php endif?><div class="company-card-body"><?php if($c['logo_path']):?><img class="company-card-logo" src="<?=e(base_url($c['logo_path']))?>" alt=""><?php endif?><h3><?=e($c['name'])?></h3><p><?=e($c['short_description']?:'Company profile in Geek Nation Multiverse.')?></p><p class="muted"><?=e(trim(($c['category']?:'').($c['location']?' · '.$c['location']:''),' ·'))?></p><a class="button ghost small" href="view.php?slug=<?=urlencode($c['slug'])?>">View Company</a></div></article><?php endforeach?><?php if(!$companies):?><article class="app-card"><h3>No companies found</h3><p class="muted">Try another search or submit the first company.</p></article><?php endif?></div></section><?php app_footer();
