<?php
require __DIR__.'/../includes/bootstrap.php';$slug=trim($_GET['slug']??'');$c=companies_schema_ready()?company_by_slug($slug):null;if(!$c){http_response_code(404);exit('Company not found.');}$u=user();if($c['status']!=='approved'&&(!$u||!can_manage_company($c,$u))){http_response_code(404);exit('Company not found.');}$members=db()->prepare("SELECT u.display_name,u.username,cm.position_title,cm.relationship_type,cm.company_role FROM company_members cm JOIN users u ON u.id=cm.user_id WHERE cm.company_id=? AND cm.status='active' AND cm.company_role<>'fan' ORDER BY FIELD(cm.company_role,'owner','company_admin','member'),u.display_name");$members->execute([(int)$c['id']]);$members=$members->fetchAll();$brands=[];if(brands_schema_ready()){$bs=db()->prepare("SELECT * FROM brands WHERE company_id=? AND status='approved' ORDER BY name");$bs->execute([(int)$c['id']]);$brands=$bs->fetchAll();}app_header($c['name']);$banner=$c['banner_path']?"background-image:linear-gradient(rgba(5,5,11,.18),rgba(5,5,11,.82)),url('".e(base_url($c['banner_path']))."')":'';
?><section class="company-profile-hero" style="<?=$banner?>"><?php if($c['logo_path']):?><img class="company-profile-logo" src="<?=e(base_url($c['logo_path']))?>" alt="<?=e($c['name'])?> logo"><?php endif?><div><p class="eyebrow">APPROVED COMPANY</p><h1><?=e($c['name'])?></h1><p><?=e($c['short_description'])?></p></div></section><section class="profile-grid"><article class="app-card profile-main"><h2>About</h2><p><?=nl2br(e($c['description']?:'No company description has been added yet.'))?></p><?php if($c['website']):?><p><a class="button primary" href="<?=e($c['website'])?>" rel="noopener" target="_blank">Visit Website</a></p><?php endif?></article><aside class="profile-side"><article class="app-card"><h2>Details</h2><dl><?php if($c['category']):?><dt>Category</dt><dd><?=e($c['category'])?></dd><?php endif?><?php if($c['location']):?><dt>Location</dt><dd><?=e($c['location'])?></dd><?php endif?><?php if($c['founded_year']):?><dt>Founded</dt><dd><?=(int)$c['founded_year']?></dd><?php endif?><?php if($c['public_email']):?><dt>Email</dt><dd><a href="mailto:<?=e($c['public_email'])?>"><?=e($c['public_email'])?></a></dd><?php endif?></dl></article><?php if($brands):?><article class="app-card"><h2>Brands</h2><?php foreach($brands as $brand):?><p><a href="<?=e(base_url('brand/view.php?slug='.urlencode($brand['slug'])))?>"><strong><?=e($brand['name'])?></strong></a><br><span class="muted"><?=e($brand['category'])?></span></p><?php endforeach?></article><?php endif?><?php if($members):?><article class="app-card"><h2>Team</h2><?php foreach($members as $m):?><p><a href="<?=e(base_url('profile.php?u='.urlencode($m['username'])))?>"><strong><?=e($m['display_name'])?></strong></a><br><span class="muted"><?=e($m['position_title']?:ucwords(str_replace('_',' ',$m['relationship_type'])))?></span></p><?php endforeach?></article><?php endif?></aside></section><?php
$relatedItems=[];
foreach(gnm_safe_rows("SELECT name,slug,tagline,COALESCE(banner_path,logo_path) AS image_path FROM booths WHERE company_id=? AND status='approved' ORDER BY is_featured DESC,updated_at DESC LIMIT 4",[(int)$c['id']]) as $row){$relatedItems[]=['title'=>$row['name'],'description'=>$row['tagline']?:'Visit this company booth.','href'=>base_url('booth/view.php?slug='.urlencode($row['slug'])),'image'=>$row['image_path']?base_url($row['image_path']):'','icon'=>'shop','eyebrow'=>'BOOTH'];}
foreach(gnm_safe_rows("SELECT e.title,e.slug,e.subtitle,COALESCE(e.thumbnail_path,e.banner_path) AS image_path,e.starts_at FROM event_relationships er JOIN events e ON e.id=er.event_id WHERE er.entity_type='company' AND er.entity_id=? AND e.status='approved' AND e.visibility='public' ORDER BY e.starts_at ASC LIMIT 4",[(int)$c['id']]) as $row){$relatedItems[]=['title'=>$row['title'],'description'=>$row['subtitle']?:date('M j, Y · g:i A',strtotime($row['starts_at'])),'href'=>base_url('events/view.php?slug='.urlencode($row['slug'])),'image'=>$row['image_path']?base_url($row['image_path']):'','icon'=>'calendar','eyebrow'=>'EVENT'];}
gnm_related_section('More from this Company','Explore Companies',base_url('company/index.php'),array_slice($relatedItems,0,8),'Company booths and events will appear here as they are connected.');
?>
<?php app_footer();
