<?php require __DIR__.'/../includes/bootstrap.php';
if(!artist_alley_ready()){app_header('Artist Alley');?><section class="form-card"><h1>Artist Alley is not installed</h1><?php if((user()['role']??'')==='admin'):?><a class="button primary" href="../upgrade-artist-alley.php">Install Artist Alley</a><?php endif?></section><?php app_footer();exit;}
$q=trim($_GET['q']??'');$commission=trim($_GET['commission']??'');
$sql="SELECT a.*,(SELECT COUNT(*) FROM artist_portfolio_items p WHERE p.artist_id=a.id) portfolio_count,(SELECT COUNT(*) FROM artist_follows f WHERE f.artist_id=a.id) follower_count FROM artist_profiles a WHERE a.status='approved'";$args=[];
if($q!==''){$sql.=' AND (a.artist_name LIKE ? OR a.headline LIKE ? OR a.specialties LIKE ?)';$args=array_fill(0,3,'%'.$q.'%');}
if(in_array($commission,['open','waitlist','closed'],true)){$sql.=' AND a.commission_status=?';$args[]=$commission;}
$sql.=' ORDER BY a.is_featured DESC,a.artist_name';$s=db()->prepare($sql);$s->execute($args);$artists=$s->fetchAll();
app_header('Artist Alley');?>
<section class="dashboard-hero artist-hero"><p class="eyebrow">CREATORS OF THE MULTIVERSE</p><h1>Artist Alley</h1><p>Discover illustrators, writers, makers, cosplayers, photographers, musicians, and independent creators.</p><form class="hero-search" method="get"><input name="q" value="<?=e($q)?>" placeholder="Search artists or specialties"><select name="commission"><option value="">All commission statuses</option><option value="open" <?=$commission==='open'?'selected':''?>>Commissions open</option><option value="waitlist" <?=$commission==='waitlist'?'selected':''?>>Waitlist</option><option value="closed" <?=$commission==='closed'?'selected':''?>>Closed</option></select><button>Search</button></form><?php if(user()):?><p><a class="button primary" href="create.php">Create Artist Profile</a> <a class="button ghost" href="dashboard.php">Manage My Artist Profile</a></p><?php endif?></section>
<section class="artist-grid"><?php foreach($artists as $artist):?><article class="artist-card"><?php if($artist['banner_path']):?><img class="artist-card-banner" src="<?=e(base_url($artist['banner_path']))?>" alt=""><?php endif?><div class="artist-card-body"><?php if($artist['avatar_path']):?><img class="artist-avatar" src="<?=e(base_url($artist['avatar_path']))?>" alt=""><?php endif?><p class="eyebrow"><?=e(strtoupper($artist['commission_status']==='open'?'COMMISSIONS OPEN':$artist['commission_status']))?></p><h2><a href="view.php?slug=<?=urlencode($artist['slug'])?>"><?=e($artist['artist_name'])?></a></h2><p><?=e($artist['headline']?:$artist['specialties'])?></p><div class="pill-row"><span class="pill"><?=(int)$artist['portfolio_count']?> works</span><span class="pill"><?=(int)$artist['follower_count']?> followers</span></div></div></article><?php endforeach?><?php if(!$artists):?><div class="empty-state"><h2>No artists found</h2><p>Try another search or create the first artist profile.</p></div><?php endif?></section>
<?php app_footer();
