<?php require __DIR__.'/../includes/bootstrap.php';if(!artist_alley_ready()){http_response_code(404);exit('Artist Alley is not installed.');}$artist=artist_by_slug($_GET['slug']??'');if(!$artist||($artist['status']!=='approved'&&!can_manage_artist($artist))){http_response_code(404);exit('Artist not found.');}
if($_SERVER['REQUEST_METHOD']==='POST'){require_auth();verify_csrf();$action=$_POST['action']??'';if($action==='follow'){db()->prepare('INSERT IGNORE INTO artist_follows(artist_id,user_id) VALUES(?,?)')->execute([$artist['id'],user()['id']]);flash('success','You are now following this artist.');}elseif($action==='unfollow'){db()->prepare('DELETE FROM artist_follows WHERE artist_id=? AND user_id=?')->execute([$artist['id'],user()['id']]);flash('success','Artist unfollowed.');}elseif($action==='commission'){if($artist['commission_status']==='closed')throw new RuntimeException('Commissions are closed.');$subject=trim($_POST['subject']??'');$brief=trim($_POST['brief']??'');if($subject===''||$brief==='')throw new RuntimeException('Subject and brief are required.');db()->prepare('INSERT INTO artist_commission_requests(artist_id,service_id,customer_user_id,subject,brief,budget) VALUES(?,?,?,?,?,?)')->execute([$artist['id'],($_POST['service_id']??'')!==''?(int)$_POST['service_id']:null,user()['id'],$subject,$brief,($_POST['budget']??'')!==''?(float)$_POST['budget']:null]);flash('success','Commission request sent.');}redirect_route('artist-alley/view.php',['slug'=>$artist['slug']]);}
$portfolio=artist_portfolio((int)$artist['id']);$services=artist_services((int)$artist['id']);$followers=(int)db()->query('SELECT COUNT(*) FROM artist_follows WHERE artist_id='.(int)$artist['id'])->fetchColumn();$following=false;if(user()){$s=db()->prepare('SELECT COUNT(*) FROM artist_follows WHERE artist_id=? AND user_id=?');$s->execute([$artist['id'],user()['id']]);$following=(bool)$s->fetchColumn();}
app_header($artist['artist_name']);?>
<section class="artist-profile-hero"<?php if($artist['banner_path']):?> style="background-image:linear-gradient(180deg,rgba(6,7,17,.25),rgba(6,7,17,.95)),url('<?=e(base_url($artist['banner_path']))?>')"<?php endif?>><?php if($artist['avatar_path']):?><img class="artist-profile-avatar" src="<?=e(base_url($artist['avatar_path']))?>" alt=""><?php endif?><div><p class="eyebrow">ARTIST ALLEY</p><h1><?=e($artist['artist_name'])?></h1><p class="lede"><?=e($artist['headline'])?></p><div class="pill-row"><span class="pill"><?=e(ucfirst($artist['commission_status']))?> commissions</span><span class="pill"><?=$followers?> followers</span></div><?php if(user()&&(int)user()['id']!==(int)$artist['user_id']):?><form method="post" class="inline-form"><?=csrf_field()?><input type="hidden" name="action" value="<?=$following?'unfollow':'follow'?>"><button class="button <?=$following?'ghost':'primary'?>"><?=$following?'Following':'Follow Artist'?></button></form><?php endif?><?php if(can_manage_artist($artist)):?> <a class="button ghost" href="manage.php?id=<?=(int)$artist['id']?>">Manage</a><?php endif?></div></section>
<div class="two-column-layout"><section><article class="app-card"><h2>About</h2><p><?=nl2br(e($artist['bio']))?></p><?php if($artist['specialties']):?><p><strong>Specialties:</strong> <?=e($artist['specialties'])?></p><?php endif?><?php if($artist['website']):?><p><a href="<?=e($artist['website'])?>" target="_blank" rel="noopener">Visit website</a></p><?php endif?></article><section class="app-card"><h2>Portfolio</h2><div class="portfolio-grid"><?php foreach($portfolio as $item):?><article class="portfolio-item"><?php if($item['media_path']):?><img src="<?=e(base_url($item['media_path']))?>" alt=""><?php endif?><div><p class="eyebrow"><?=e(strtoupper($item['item_type']))?></p><h3><?=e($item['title'])?></h3><p><?=e($item['description'])?></p><?php if($item['external_url']):?><a href="<?=e($item['external_url'])?>" target="_blank" rel="noopener">View project</a><?php endif?></div></article><?php endforeach?><?php if(!$portfolio):?><p class="muted">No portfolio work has been published yet.</p><?php endif?></div></section></section><aside><section class="app-card"><h2>Commission Services</h2><?php foreach($services as $service):?><div class="service-card"><h3><?=e($service['title'])?></h3><p><?=e($service['description'])?></p><strong>From $<?=number_format((float)$service['price_from'],2)?></strong><?php if($service['turnaround_days']):?><small><?= (int)$service['turnaround_days']?> day estimate</small><?php endif?></div><?php endforeach?><?php if(!$services):?><p class="muted">No services listed.</p><?php endif?></section><?php if(user()&&(int)user()['id']!==(int)$artist['user_id']&&$artist['commission_status']!=='closed'):?><section class="app-card"><h2>Request a Commission</h2><form method="post" class="stack-form"><?=csrf_field()?><input type="hidden" name="action" value="commission"><label>Service<select name="service_id"><option value="">General request</option><?php foreach($services as $service):?><option value="<?=(int)$service['id']?>"><?=e($service['title'])?></option><?php endforeach?></select></label><label>Subject<input name="subject" required></label><label>Budget<input name="budget" type="number" min="0" step="0.01"></label><label>Creative brief<textarea name="brief" rows="6" required></textarea></label><button class="button primary">Send Request</button></form></section><?php endif?></aside></div>
<?php
$relatedItems=[];
foreach(gnm_safe_rows("SELECT e.title,e.slug,e.subtitle,e.thumbnail_path,e.banner_path,e.starts_at FROM event_speakers es JOIN events e ON e.id=es.event_id WHERE es.user_id=? AND e.status='approved' AND e.visibility='public' ORDER BY e.starts_at ASC LIMIT 4",[(int)$artist['user_id']]) as $row){
 $relatedItems[]=['title'=>$row['title'],'description'=>$row['subtitle']?:date('M j, Y · g:i A',strtotime($row['starts_at'])),'href'=>base_url('events/view.php?slug='.urlencode($row['slug'])),'image'=>base_url($row['thumbnail_path']?:$row['banner_path']?:$artist['avatar_path']?:'assets/geek-nation-multiverse-logo.png'),'eyebrow'=>'APPEARANCE'];
}
foreach(gnm_safe_rows("SELECT c.title,c.slug,c.subtitle,c.thumbnail_path FROM academy_instructors ai JOIN academy_courses c ON c.id=ai.course_id WHERE ai.user_id=? AND c.status='approved' ORDER BY c.is_featured DESC,c.updated_at DESC LIMIT 4",[(int)$artist['user_id']]) as $row){
 $relatedItems[]=['title'=>$row['title'],'description'=>$row['subtitle']?:'Learn with this creator.','href'=>base_url('academy/view.php?slug='.urlencode($row['slug'])),'image'=>base_url($row['thumbnail_path']?:$artist['avatar_path']?:'assets/geek-nation-multiverse-logo.png'),'eyebrow'=>'COURSE'];
}
foreach(gnm_safe_rows("SELECT name,slug,tagline,logo_path,banner_path FROM booths WHERE owner_user_id=? AND status='approved' ORDER BY is_featured DESC,updated_at DESC LIMIT 4",[(int)$artist['user_id']]) as $row){
 $relatedItems[]=['title'=>$row['name'],'description'=>$row['tagline']?:'Shop this creator’s booth.','href'=>base_url('booth/view.php?slug='.urlencode($row['slug'])),'image'=>base_url($row['banner_path']?:$row['logo_path']?:$artist['avatar_path']?:'assets/geek-nation-multiverse-logo.png'),'eyebrow'=>'BOOTH'];
}
gnm_related_section('More from this Artist','Explore Artist Alley',base_url('artist-alley/index.php'),array_slice($relatedItems,0,8),'Appearances, courses, and booths connected to this artist will appear here.');
?>
<?php app_footer();
