<?php require __DIR__.'/../includes/bootstrap.php';if(!events_schema_ready())redirect('events/index.php');$event=event_by_slug(trim($_GET['slug']??''));if(!$event||($event['status']!=='approved'&& !can_manage_event($event))){http_response_code(404);exit('Event not found.');}record_event_view((int)$event['id']);$speakers=event_speakers((int)$event['id']);$relationships=event_relationships((int)$event['id']);$u=user();$attendance=null;if($u){$s=db()->prepare('SELECT * FROM event_attendees WHERE event_id=? AND user_id=?');$s->execute([$event['id'],$u['id']]);$attendance=$s->fetch()?:null;}if($_SERVER['REQUEST_METHOD']==='POST'){require_auth();verify_csrf();$action=$_POST['action']??'';if($action==='rsvp'&&$event['registration_mode']==='open'){event_rsvp((int)$event['id'],(int)user()['id'],(int)($event['capacity']??0));flash('success','Your RSVP has been recorded.');}elseif($action==='cancel'){db()->prepare("UPDATE event_attendees SET attendee_status='cancelled' WHERE event_id=? AND user_id=?")->execute([$event['id'],user()['id']]);flash('success','Your RSVP was cancelled.');}redirect_route('events/view.php',['slug'=>$event['slug']]);}app_header($event['title']);?>
<section class="event-hero"<?php if($event['banner_path']):?> style="background-image:linear-gradient(90deg,rgba(5,6,15,.94),rgba(5,6,15,.45)),url('<?=e(base_url($event['banner_path']))?>')"<?php endif?>><p class="eyebrow"><?=e(strtoupper(event_type_options()[$event['event_type']]??$event['event_type']))?></p><h1><?=e($event['title'])?></h1><?php if($event['subtitle']):?><p class="lead"><?=e($event['subtitle'])?></p><?php endif?><div class="event-meta"><span><?=e(event_date_label($event))?></span><span><?=e($event['timezone'])?></span><span><?=e(ucfirst($event['format']))?></span></div><?php if($u):?><form method="post" class="inline-form"><?=csrf_field()?><?php if(!$attendance||$attendance['attendee_status']==='cancelled'):?><input type="hidden" name="action" value="rsvp"><button class="button primary" <?=$event['registration_mode']!=='open'?'disabled':''?>>RSVP</button><?php else:?><input type="hidden" name="action" value="cancel"><button class="button ghost">Cancel RSVP</button><span class="pill"><?=e(ucfirst($attendance['attendee_status']))?></span><?php endif?></form><?php else:?><a class="button primary" href="../login.php">Sign in to RSVP</a><?php endif?></section>
<section class="event-layout"><article class="app-card event-main"><h2>About This Event</h2><div class="prose"><?=nl2br(e($event['description']))?></div><?php if($speakers):?><h2>Speakers & Guests</h2><div class="speaker-grid"><?php foreach($speakers as $speaker):?><div class="speaker-card"><h3><?=e($speaker['name'])?></h3><p class="eyebrow"><?=e($speaker['role'])?></p><p><?=e($speaker['bio'])?></p></div><?php endforeach?></div><?php endif?></article><aside class="app-card"><h2>Location</h2><?php if(in_array($event['format'],['physical','hybrid'],true)):?><p><strong><?=e($event['venue_name']?:'Physical location')?></strong><br><?=e(trim(implode(', ',array_filter([$event['address1'],$event['city'],$event['state_region'],$event['postal_code']]))))?></p><?php endif?><?php if(in_array($event['format'],['virtual','hybrid'],true)):?><p><?php if($event['virtual_url']):?><a class="button primary" href="<?=e($event['virtual_url'])?>" rel="noopener">Open Virtual Event</a><?php else:?>Virtual link will be announced.<?php endif?></p><?php endif?><h2>Hosted By</h2><p><?=e($event['owner_name'])?></p><?php if($relationships):?><h2>Related</h2><?php foreach($relationships as $r):?><p><span class="pill"><?=e(ucfirst($r['entity_type']))?></span> <?=e($r['entity_name'])?></p><?php endforeach?><?php endif?></aside></section><?php
$relatedItems=[];
foreach(gnm_safe_rows("SELECT er.entity_type,er.entity_id FROM event_relationships er WHERE er.event_id=? LIMIT 12",[(int)$event['id']]) as $rel){
 if($rel['entity_type']==='universe'){$rows=gnm_safe_rows("SELECT name,slug,short_description,banner_path FROM universes WHERE id=? AND status='approved' AND is_active=1",[(int)$rel['entity_id']]);$prefix='universe/view.php';$label='UNIVERSE';}
 elseif($rel['entity_type']==='booth'){$rows=gnm_safe_rows("SELECT name,slug,tagline AS short_description,COALESCE(banner_path,logo_path) AS banner_path FROM booths WHERE id=? AND status='approved'",[(int)$rel['entity_id']]);$prefix='booth/view.php';$label='BOOTH';}
 elseif($rel['entity_type']==='company'){$rows=gnm_safe_rows("SELECT name,slug,short_description,COALESCE(banner_path,logo_path) AS banner_path FROM companies WHERE id=? AND status='approved'",[(int)$rel['entity_id']]);$prefix='company/view.php';$label='COMPANY';}
 else{$rows=gnm_safe_rows("SELECT name,slug,short_description,COALESCE(banner_path,logo_path) AS banner_path FROM brands WHERE id=? AND status='approved'",[(int)$rel['entity_id']]);$prefix='brand/view.php';$label='BRAND';}
 foreach($rows as $row)$relatedItems[]=['title'=>$row['name'],'description'=>$row['short_description']?:'Explore this event connection.','href'=>base_url($prefix.'?slug='.urlencode($row['slug'])),'image'=>$row['banner_path']?base_url($row['banner_path']):'','icon'=>'spark','eyebrow'=>$label];
}
foreach($speakers as $speaker){if(!empty($speaker['user_id'])){$rows=gnm_safe_rows("SELECT artist_name AS name,slug,headline AS short_description,avatar_path AS banner_path FROM artist_profiles WHERE user_id=? AND status='approved'",[(int)$speaker['user_id']]);foreach($rows as $row)$relatedItems[]=['title'=>$row['name'],'description'=>$row['short_description']?:'Meet this event speaker.','href'=>base_url('artist-alley/view.php?slug='.urlencode($row['slug'])),'image'=>$row['banner_path']?base_url($row['banner_path']):'','icon'=>'users','eyebrow'=>'SPEAKER'];}}
gnm_related_section('Explore Event Connections','Explore Panels & Events',base_url('events/index.php'),array_slice($relatedItems,0,8),'Speakers, booths, brands, companies, and universes connected to this event will appear here.');
?>
<?php app_footer();
